name: Demo-CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Steps
        run: echo "Hello worldi"
